version: "3"
services:
  postgres:
    container_name: kurs_postgres
    image: postgres:14.2-alpine
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: kurs
      POSTGRES_DB: kurs
      PG_DATA: /var/lib/postgresql/data
    ports:
      - 5455:5432
    volumes:
      - pgdatakurs:/var/lib/postgresql/data
volumes:
  pgdatakurs: